# Generated by Django 3.2.5 on 2021-07-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idol',
            name='voice_actor',
        ),
        migrations.AddField(
            model_name='idol',
            name='romanized_voice_actor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='idol',
            name='voice_actor_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
