# Generated by Django 3.2.5 on 2021-07-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20201216_1732'),
        ('idols', '0002_auto_20210709_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceActor',
        ),
        migrations.AddField(
            model_name='idol',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='categories.branch'),
            preserve_default=False,
        ),
    ]
