# Generated by Django 3.1.4 on 2020-12-15 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0003_auto_20201215_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('romanized_title', models.CharField(max_length=255)),
                ('impression', models.TextField(blank=True)),
                ('arranger', models.ManyToManyField(blank=True, related_name='arranged_songs', to='artists.Artist')),
                ('composer', models.ManyToManyField(blank=True, related_name='composed_songs', to='artists.Artist')),
                ('lyricist', models.ManyToManyField(blank=True, related_name='written_songs', to='artists.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='OutsideSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('romanized_title', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('composer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
