# Generated by Django 3.1.4 on 2020-12-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20201216_1622'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outsidesong',
            name='origin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outsidesong',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outsidesong',
            name='url',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.branch'),
        ),
        migrations.AlterField(
            model_name='song',
            name='romanized_title',
            field=models.CharField(max_length=255),
        ),
    ]
