# Generated by Django 3.1.4 on 2020-12-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20201216_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-branch__acronym', 'romanized_title', 'title']},
        ),
    ]
