# Generated by Django 3.1.4 on 2020-12-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20201216_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyricist',
        ),
    ]
