# Generated by Django 3.1.4 on 2020-12-16 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_remove_song_lyricist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='branch',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='songs.branch'),
            preserve_default=False,
        ),
    ]
