# Generated by Django 3.2.5 on 2021-07-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idols', '0001_initial'),
        ('songs', '0005_song_idols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='idols',
            field=models.ManyToManyField(blank=True, related_name='idol_songs', to='idols.Idol'),
        ),
    ]
