# Generated by Django 3.1.4 on 2020-12-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20201216_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='romanized_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
