# Generated by Django 3.1.4 on 2020-12-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20201216_0724'),
        ('songs', '0006_auto_20201216_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyricist',
            field=models.ManyToManyField(blank=True, related_name='written_songs', to='artists.Artist'),
        ),
    ]
