# Generated by Django 3.1.4 on 2020-12-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song_lyricist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outsidesong',
            options={'ordering': ['composer', 'title']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['romanized_title', 'title']},
        ),
    ]
