# Generated by Django 3.1.4 on 2020-12-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20201216_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='color',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
