# Generated by Django 3.1.4 on 2020-12-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_branch_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='color',
            new_name='background_color',
        ),
        migrations.AddField(
            model_name='branch',
            name='foreground_color',
            field=models.CharField(default='#000000', max_length=10),
        ),
    ]
