# Generated by Django 3.1.4 on 2020-12-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_auto_20201216_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='foreground_color',
        ),
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
