# Generated by Django 3.1.4 on 2020-12-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_auto_20201216_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
    ]
