# Generated by Django 3.2.5 on 2021-07-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_auto_20201216_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
