# Generated by Django 3.1.4 on 2020-12-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('romanized_name', models.CharField(blank=True, max_length=255)),
                ('about_composer', models.TextField(blank=True)),
                ('about_music', models.TextField(blank=True)),
                ('aliases', models.ManyToManyField(blank=True, related_name='_artist_aliases_+', to='artists.Artist')),
                ('category', models.ManyToManyField(blank=True, to='categories.Category')),
            ],
            options={
                'ordering': ['romanized_name', 'name'],
            },
        ),
    ]
