# Generated by Django 3.1.4 on 2020-12-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201215_2054'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='category',
            field=models.ManyToManyField(blank=True, to='categories.Category'),
        ),
    ]
