# Generated by Django 3.1.4 on 2020-12-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='about_composer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='about_music',
            field=models.TextField(blank=True),
        ),
    ]
