# Generated by Django 3.1.4 on 2020-12-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='romanized_name',
            field=models.CharField(max_length=255),
        ),
    ]
