# Generated by Django 3.1.4 on 2020-12-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20201216_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='about_composer',
            new_name='about_artist',
        ),
    ]
