# Generated by Django 3.1.4 on 2020-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20201215_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artist',
            name='romanized_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
