# Generated by Django 3.1.4 on 2020-12-16 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20201216_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['romanized_name', 'name']},
        ),
    ]
