# Generated by Django 3.2.5 on 2021-07-09 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_alter_song_idols'),
        ('artists', '0005_idol_voiceactor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Idol',
        ),
        migrations.DeleteModel(
            name='VoiceActor',
        ),
    ]
