# Generated by Django 4.0.5 on 2022-06-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='aliases',
            field=models.ManyToManyField(blank=True, to='artists.artist'),
        ),
    ]
